CIRCLE-35361: Add known outgoing ips for core services
CircleCI-Public/known-outgoing-ip-preview-docs pull request #1
Opened 2021-06-10 18:35 UTC by brentmmarks

2021-06-14 12:56 UTC, SemanticallyNull requested changes

2021-06-14 12:56 UTC, SemanticallyNull commented on README.md
> +"54.92.235.88",
We should probably keep these separate and explain to customers what sorts of requests can come from which IP addresses.

2021-06-14 13:06 UTC, brentmmarks commented on README.md
> +"54.92.235.88",
Updated, let me know if this covers what you were thinking.

2021-06-16 13:37 UTC, DominicLavery commented on README.md
> +Known IPs for the core service (API, etc - to trigger jobs, exchange information on users between CircleCI and Github):
```suggestion
Known IPs for the core services (used to trigger jobs, exchange information about users between CircleCI and Github etc):
```
~ I was a little confused about what this was trying to say at first. Would this be a bit clearer?

2021-06-16 14:01 UTC, DominicLavery approved these changes

2021-06-16 14:15 UTC, merged